url: "https://seoengr.net" # the base hostname & protocol for your site, e.g. http://example.com
title: "SEOEngineering"
tagline: "Technical SEO blog"
description: "Technical SEO blog, if you like code and search engines you belong here."
twitter:
  username: "seoengr"
  card: "summary"
logo: /assets/images/site_wide_logo.png

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-validator

postcss:
  cache: false

validator:
  exclude: 
    - 'assets/css/main.css'
